version: "3.8"
services:
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - ../../models:/app/models # relative path (two levels up from the deploy folder)
    networks:
      - wine_network
    

  app:
    build:
      context: ./app
    ports:
      - "8501:8501"
    networks:
      - wine_network
    depends_on:
      - api
    volumes:
      - ../../models:/app/models

networks:
  wine_network:
    driver: bridge